import { destinationImg } from "./img";
import { transportImg } from "./TransportImges";

export const destinationsData = [
    {
        name: 'La Ceiba',
        img: destinationImg.ceiba,
        description: 'La Ceiba',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '4:00 AM',
            final: '6:30 AM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '6:00 AM',
            final: '9:00 AM',
            transport: 'A-32',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '8:00 AM',
            final: '11:00 AM',
            transport: 'A-33',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '10:00 AM',
            final: '01:00 PM',
            transport: 'A-33',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '02:00 PM',
            final: '05:00 PM',
            transport: 'A-34',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '04:00 PM',
            final: '07:00 PM',
            transport: 'A-35',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '06:00 PM',
            final: '09:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
    ],
    }, 
    {
        name: 'Tela',
        img: destinationImg.tela,
        description: 'Tela',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'San Juan Pueblo',
        img: destinationImg.sanJuanPueblo,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'El Progreso',
        img: destinationImg.elProgreso,
        description: 'Yoro',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'La Másica',
        img: destinationImg.masicaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Terminal Metropolitana',
        img: destinationImg.terminalMetropolitanaSanPedroSula,
        description: 'San Pedro Sula',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Villanueva',
        img: destinationImg.villanuevaCortes,
        description: 'Cortes',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Olancho',
        img: destinationImg.olancho,
        description: 'Olancho',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Jutiapa',
        img: destinationImg.jutiapaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Roma, Jutiapa',
        img: destinationImg.romaJutiapaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'San Ana',
        img: destinationImg.santaAnaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Terminal Metropolitana',
        img: destinationImg.terminalMetropolitanaSanPedroSula,
        description: 'San Pedro Sula',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Villanueva',
        img: destinationImg.villanuevaCortes,
        description: 'Cortes',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Olancho',
        img: destinationImg.olancho,
        description: 'Olancho',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Jutiapa',
        img: destinationImg.jutiapaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'Roma, Jutiapa',
        img: destinationImg.romaJutiapaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
    {
        name: 'San Ana',
        img: destinationImg.santaAnaAtlantida,
        description: 'Atlántida',
        schedulers: [{
            origen: 'Central Metropolitana',
            destination: 'La Ceiba',
            output: '2:00 PM',
            final: '5:00 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'San Juan Pueblo',
            transport: 'A-31',
            output: '3:00 PM',
            final: '5:00 PM',
            capacity: 52,
            available: 10,
            bus: transportImg.bus2,
        },
        {
            origen: 'Central Metropolitana',
            destination: 'Tela',
            output: '2:00 PM',
            final: '3:30 PM',
            transport: 'A-31',
            capacity: 52,
            available: 10,
            bus: transportImg.bus1,
        }],
    },
];